baseurl: "/ja/docs"

collections:
  cci2:
    # Turn this off because we output the JA version onto the same path this would use
    output: false
  cci2_ja:
    name: "2.0 Docs"
    site_section: true
    output: true
    permalink: /2.0/:path/
    prefix: "/2.0"
    selectorName: "2.0"
